#!/usr/bin/env python3
"""
Quotient degree-drop scout for T_1^(8,2) in the P15 n=8 defect atlas.

This script tests the first two nonzero extra-defect complement shapes in the
fixed-plus family lambda_plus=1:

    (6,1) through the 1-subset permutation module on each 7-point complement;
    (5,2) through the 2-subset permutation module modulo its star submodule.

The point is not to classify the full fingerprint. It records a finite n=8
mechanism: the compressed operator has a lower quotient profile whose modular
ranks match the corresponding Specht blocks.
"""
from __future__ import annotations

import argparse
import itertools
import json
import time
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np

from p15_full_bn_prespecht_fixed_plus_scout import (
    block_matrix_mod,
    build_prespecht_terms,
    mod_rank,
    needed_specht_matrices,
)


ROOT = Path(__file__).resolve().parents[1]
PRIME = 1000003


@dataclass(frozen=True)
class LayerProfile:
    r: int
    specht_shape: str
    natural_dim: int
    lower_subspace_description: str
    lower_column_count: int
    lower_rank: int
    natural_operator_rank: int
    concatenated_lower_image_rank: int
    image_mod_lower_rank: int
    image_intersection_lower_rank: int
    source_lower_image_rank: int
    source_lower_image_outside_lower_rank: int
    specht_dim: int
    specht_block_rank: int
    pass_conditions: Dict[str, bool]


@dataclass(frozen=True)
class QuotientScoutSummary:
    status: str
    claim: str
    n: int
    k: int
    lambda_plus: str
    complement_size: int
    prime: int
    subset_count: int
    group_keys: int
    profiles: List[LayerProfile]
    runtime_seconds: float
    boundary: str
    next_task: str


def part_str(part: Tuple[int, ...]) -> str:
    return ".".join(str(x) for x in part) if part else "empty"


def complement_points(n: int, plus_mask: int) -> List[int]:
    return [x for x in range(n) if not ((plus_mask >> x) & 1)]


def natural_basis(n: int, r: int, plus_masks: List[int]) -> Tuple[List[Tuple[int, Tuple[int, ...]]], Dict[Tuple[int, Tuple[int, ...]], int]]:
    basis: List[Tuple[int, Tuple[int, ...]]] = []
    index: Dict[Tuple[int, Tuple[int, ...]], int] = {}
    for plus_index, plus_mask in enumerate(plus_masks):
        comp = complement_points(n, plus_mask)
        for sub in itertools.combinations(comp, r):
            key = (plus_index, tuple(sub))
            index[key] = len(basis)
            basis.append(key)
    return basis, index


def natural_operator_matrix(n: int, r: int, plus_masks: List[int], grouped, p: int) -> np.ndarray:
    basis, index = natural_basis(n, r, plus_masks)
    dim = len(basis)
    M = np.zeros((dim, dim), dtype=np.int64)
    for (dst_i, src_i, sigma), coeff in grouped.items():
        src_comp = complement_points(n, plus_masks[src_i])
        dst_comp = complement_points(n, plus_masks[dst_i])
        for sub in itertools.combinations(src_comp, r):
            source_ranks = [src_comp.index(x) for x in sub]
            image = tuple(sorted(dst_comp[sigma[t]] for t in source_ranks))
            row = index[(dst_i, image)]
            col = index[(src_i, tuple(sub))]
            M[row, col] = (M[row, col] + coeff) % p
    return M


def lower_subspace_matrix(n: int, r: int, plus_masks: List[int]) -> Tuple[np.ndarray, str]:
    basis, index = natural_basis(n, r, plus_masks)
    columns: List[np.ndarray] = []
    if r == 1:
        desc = "fiber constants U_0 in the 1-subset module"
        for plus_index, plus_mask in enumerate(plus_masks):
            v = np.zeros((len(basis),), dtype=np.int64)
            comp = complement_points(n, plus_mask)
            for sub in itertools.combinations(comp, r):
                v[index[(plus_index, tuple(sub))]] = 1
            columns.append(v)
    elif r == 2:
        desc = "fiber star subspace U_1 generated by point-stars in the 2-subset module"
        for plus_index, plus_mask in enumerate(plus_masks):
            comp = complement_points(n, plus_mask)
            for x in comp:
                v = np.zeros((len(basis),), dtype=np.int64)
                for sub in itertools.combinations(comp, r):
                    if x in sub:
                        v[index[(plus_index, tuple(sub))]] = 1
                columns.append(v)
    else:
        raise ValueError(f"unsupported r={r}")
    return np.stack(columns, axis=1), desc


def specht_rank_for_shape(shape: Tuple[int, ...], subset_count: int, grouped, p: int) -> Tuple[int, int]:
    sigmas = {sigma for (_dst, _src, sigma) in grouped}
    mats, dim = needed_specht_matrices(shape, sigmas, p)
    block = block_matrix_mod(grouped, subset_count, mats, dim, p)
    return dim, mod_rank(block, p)


def profile_for_r(
    n: int,
    r: int,
    shape: Tuple[int, ...],
    expected_natural_rank: int,
    expected_image_mod_lower: int,
    expected_source_lower_image: int,
    plus_masks: List[int],
    grouped,
    p: int,
) -> LayerProfile:
    M = natural_operator_matrix(n, r, plus_masks, grouped, p)
    B, desc = lower_subspace_matrix(n, r, plus_masks)
    rank_M = mod_rank(M, p)
    rank_B = mod_rank(B, p)
    concat_rank = mod_rank(np.hstack([B, M]), p)
    image_mod_lower = concat_rank - rank_B
    intersection = rank_M + rank_B - concat_rank
    MB = (M @ B) % p
    source_lower_image_rank = mod_rank(MB, p)
    source_lower_outside = mod_rank(np.hstack([B, MB]), p) - rank_B
    specht_dim, specht_rank = specht_rank_for_shape(shape, len(plus_masks), grouped, p)
    checks = {
        "natural_rank_matches_expected": rank_M == expected_natural_rank,
        "image_mod_lower_matches_expected": image_mod_lower == expected_image_mod_lower,
        "source_lower_image_rank_matches_expected": source_lower_image_rank == expected_source_lower_image,
        "source_lower_maps_inside_lower": source_lower_outside == 0,
        "specht_rank_matches_quotient_rank": specht_rank == image_mod_lower,
    }
    return LayerProfile(
        r=r,
        specht_shape=part_str(shape),
        natural_dim=M.shape[0],
        lower_subspace_description=desc,
        lower_column_count=B.shape[1],
        lower_rank=rank_B,
        natural_operator_rank=rank_M,
        concatenated_lower_image_rank=concat_rank,
        image_mod_lower_rank=image_mod_lower,
        image_intersection_lower_rank=intersection,
        source_lower_image_rank=source_lower_image_rank,
        source_lower_image_outside_lower_rank=source_lower_outside,
        specht_dim=specht_dim,
        specht_block_rank=specht_rank,
        pass_conditions=checks,
    )


def certify(out_json: Path | None, out_md: Path | None) -> QuotientScoutSummary:
    t0 = time.time()
    n = 8
    k = 2
    plus_masks, grouped, _perms, _raw_active, _raw_abs, _zero_removed = build_prespecht_terms(n, k, 1)
    profiles = [
        profile_for_r(
            n=n,
            r=1,
            shape=(6, 1),
            expected_natural_rank=12,
            expected_image_mod_lower=12,
            expected_source_lower_image=0,
            plus_masks=plus_masks,
            grouped=grouped,
            p=PRIME,
        ),
        profile_for_r(
            n=n,
            r=2,
            shape=(5, 2),
            expected_natural_rank=48,
            expected_image_mod_lower=36,
            expected_source_lower_image=12,
            plus_masks=plus_masks,
            grouped=grouped,
            p=PRIME,
        ),
    ]
    status = "PASS" if all(all(p.pass_conditions.values()) for p in profiles) else "FAIL"
    summary = QuotientScoutSummary(
        status=status,
        claim=(
            "For the fixed-plus compressed operator T_1^(8,2), the first two nonzero "
            "extra-defect complement rows are explained by natural quotient layers: "
            "the 1-subset module modulo fiber constants gives rank 12 and matches "
            "S^(6,1); the 2-subset module modulo the fiber star subspace gives "
            "rank 36 and matches S^(5,2)."
        ),
        n=n,
        k=k,
        lambda_plus="1",
        complement_size=7,
        prime=PRIME,
        subset_count=len(plus_masks),
        group_keys=len(grouped),
        profiles=profiles,
        runtime_seconds=round(time.time() - t0, 3),
        boundary=(
            "Finite n=8,k=2 modular quotient-degree scout only. It explains the "
            "(6,1) and (5,2) rows of the lambda_plus=1 family; later quotient, sign-twist, "
            "and residual certificates complete the finite T_1^(8,2) accounting. It does "
            "not prove an all-n theorem."
        ),
        next_task=(
            "Attack the next compact one-row fixed-plus family T_4^(8,3) (lambda_plus=4, n=8,k=3), "
            "and keep this package appendix-scoped; rational T_1/T_2/T_4 audits are separate optional checks."
        ),
    )
    if out_json:
        out_json.parent.mkdir(parents=True, exist_ok=True)
        out_json.write_text(json.dumps(asdict(summary), indent=2), encoding="utf-8")
    if out_md:
        out_md.parent.mkdir(parents=True, exist_ok=True)
        write_markdown(summary, out_md)
    return summary


def write_markdown(summary: QuotientScoutSummary, path: Path) -> None:
    lines = [
        "# P15 T1 k=2 Quotient Degree-Drop Scout",
        "",
        f"Status: **{summary.status}**",
        "",
        "## Claim",
        "",
        "```text",
        summary.claim,
        "```",
        "",
        "## Profiles",
        "",
        "| r | quotient Specht | natural dim | lower rank | rank(M) | image mod lower | image cap lower | M(lower) rank | outside lower | Specht rank |",
        "|---:|---|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for p in summary.profiles:
        lines.append(
            f"| {p.r} | `{p.specht_shape}` | {p.natural_dim} | {p.lower_rank} | "
            f"{p.natural_operator_rank} | {p.image_mod_lower_rank} | "
            f"{p.image_intersection_lower_rank} | {p.source_lower_image_rank} | "
            f"{p.source_lower_image_outside_lower_rank} | {p.specht_block_rank} |"
        )
    lines += [
        "",
        "## Reading",
        "",
        "For `r=1`, the lower space is the 8-dimensional space of constants on each 7-point complement fiber. The operator kills these source constants, and the image has no intersection with the lower space. The quotient image has rank 12, exactly the rank of the Specht block `(6,1)`.",
        "",
        "For `r=2`, the lower space is the 56-dimensional star subspace generated by point-stars in each 7-point complement fiber. The operator maps this lower source space back into the lower target space with rank 12. The full natural 2-subset image has rank 48, and its image modulo the lower star subspace has rank 36, exactly the rank of the Specht block `(5,2)`.",
        "",
        "Thus the observed split is:",
        "",
        "```text",
        "r=1: standard quotient rank = 12.",
        "r=2: lower contribution rank 12 plus top quotient rank 36 = natural rank 48.",
        "```",
        "",
        "## Checks",
        "",
    ]
    for p in summary.profiles:
        lines += [
            f"### r={p.r}, Specht `{p.specht_shape}`",
            "",
            "```json",
            json.dumps(p.pass_conditions, indent=2),
            "```",
            "",
        ]
    lines += [
        "## Sources",
        "",
        "```text",
        "scripts/p15_full_bn_t1_k2_quotient_degree_drop_scout.py",
        "certified/P15_FULL_BN_T1_K2_QUOTIENT_DEGREE_DROP_SCOUT.json",
        "certified/P15_FULL_BN_T1_K2_QUOTIENT_DEGREE_DROP_SCOUT.md",
        "```",
        "",
        "## Boundary",
        "",
        summary.boundary,
        "",
        "Prossima task: " + summary.next_task,
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write-json", default=None)
    ap.add_argument("--write-md", default=None)
    args = ap.parse_args()
    summary = certify(Path(args.write_json) if args.write_json else None, Path(args.write_md) if args.write_md else None)
    print(json.dumps(asdict(summary), indent=2))
    return 0 if summary.status == "PASS" else 2


if __name__ == "__main__":
    raise SystemExit(main())
